### PR TITLE
fix(print): fixed padding for printing 10

### LINKED ISSUE #7: Printing a card of rank 10 will result in distorted card design
### Issue
Whenever a card with rank `10` is being printed in console, the card edges will be too wide on that particular line resulting in a glitch. 

### Solution 
This should be fixed by using correct padding for printing cards, maybe even change the card width?
```javascript
// Print a single card
function printCard (card) {
  console.log('-----------')
  console.log('| ' + getSymbol(card.suit) + '       |')
  console.log('|         |')
  if (card.rank === 10) {
    console.log('|    ' + card.rank + '   |')
  } else {
    console.log('|    ' + card.rank + '    |')
  }
  console.log('|         |')
  console.log('|       ' + getSymbol(card.suit) + ' |')
  console.log('-----------')
}
``` 

10 is already handled exclusively? Width still not displayed properly, need to check dimensions.

### PR DESCRIPTION
**Pull request by suptower**
Closes #7, fix has been tested as well.

### CODE REVIEW

File: game.js [hunk 1]
```diff
@@ -62,7 +62,8 @@ function printCard (card) {
   console.log('-----------')
   console.log('| ' + getSymbol(card.suit) + '       |')
   console.log('|         |')
-  if (card.rank === 10) {
+  if (card.rank === '10') {
```
Comment (suptower) [inline game.js:65]: This condition was not able to be true since the rank of a card is not a number but a string.
Comparing the rank to a string consisting of '10' fixed the issue.

File: game.js [hunk 2]
```diff
@@ -121,7 +122,8 @@ function printHand (hand) {
     output[0] += '----------- '
     output[1] += '| ' + getSymbol(card.suit) + '       | '
     output[2] += '|         | '
-    if (card.rank === 10) {
+    if (card.rank === '10') {
```
Comment (suptower) [inline game.js:125]: Same as for printing a single card applies to printing hands.
This condition was not able to be true since the rank of a card is not a number but a string.
Comparing the rank to a string consisting of '10' fixed the issue.

**Review by suptower — COMMENTED** [review]
Changes have been commented accordingly.
